import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MoviesProvider } from '@/contexts'
import { Navbar } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MoviesProvider>
          <Navbar />
          <main className='min-h-screen'>          
            {children}
        </main>
        </MoviesProvider>
        </body>
    </html>
  )
}
